# Generated by Django 6.1.1 on 2026-09-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("customer_phone", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("pickup", "Самовивіз"),
                            ("courier", "Кур'єрська доставка"),
                        ],
                        max_length=10,
                    ),
                ),
                ("delivery_address", models.CharField(blank=True, max_length=255)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Готівка"),
                            ("transfer", "Безготівковий переказ"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Очікує підтвердження"),
                            ("confirmed", "Підтверджено"),
                            ("active", "Триває"),
                            ("completed", "Завершено"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("rental_days", models.PositiveSmallIntegerField()),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="locations.city",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
