# Generated by Django 6.1.1 on 2026-09-24 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_callbackrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callbackrequest",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введіть номер у форматі +380XXXXXXXXX.",
                        regex="^\\+380\\d{9}$",
                    )
                ],
            ),
        ),
    ]
