# Generated by Django 6.1.1 on 2026-09-24 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_alter_callbackrequest_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="customer_email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer_phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введіть номер у форматі +380XXXXXXXXX.",
                        regex="^\\+380\\d{9}$",
                    )
                ],
            ),
        ),
    ]
